# Generated by Django 3.2.7 on 2021-10-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('description', models.CharField(default='Device credential description', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Nonactive'), (1, 'Active'), (2, 'To bin')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('device_type', models.IntegerField(choices=[(0, 'Unknown device'), (1, 'Cisco IOS'), (2, 'Cisco IOSXR'), (3, 'Cisco IOSXE'), (4, 'Cisco NXOS')], default=0)),
                ('ico', models.IntegerField(choices=[(0, 'Unknown device'), (1, 'Cisco IOS'), (2, 'Cisco IOSXR'), (3, 'Cisco IOSXE'), (4, 'Cisco NXOS')], default=1)),
                ('ssh_port', models.IntegerField(default=22)),
                ('https_port', models.IntegerField(default=443)),
                ('certificate', models.BooleanField(default=False)),
                ('description', models.CharField(default='Device description', max_length=512)),
                ('ssh_status', models.BooleanField(default=False)),
                ('https_status', models.BooleanField(default=False)),
                ('ping_status', models.BooleanField(default=False)),
                ('credential', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.credential')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=64)),
                ('description', models.CharField(default='Color description', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TagDeviceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.device')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.tag')),
            ],
            options={
                'unique_together': {('device', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='devices',
            field=models.ManyToManyField(through='management.TagDeviceRelation', to='management.Device'),
        ),
        migrations.AddField(
            model_name='credential',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='management.tag'),
        ),
    ]
