# Generated by Django 3.2.7 on 2021-10-28 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
