# Generated by Django 3.2.7 on 2021-10-05 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_device_ico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='color',
        ),
    ]
