# Generated by Django 3.2.7 on 2021-10-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_credential_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='value',
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='ffffff', error_messages={'blank': 'This field is mandatory', 'null': 'This field is mandatory'}, help_text='Hexadecimal representation of colour, for example 73a6ff.', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='management.credential'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'CiscoIOS'), (2, 'CiscoIOSXR'), (3, 'CiscoIOSXE'), (4, 'CiscoNXOS')], default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ico',
            field=models.IntegerField(choices=[(0, 'static/management/svg/router.svg'), (1, 'static/management/svg/asa-5500.svg'), (2, 'static/management/svg/atm-router.svg'), (3, 'static/management/svg/cisco-asa-5500.svg'), (4, 'static/management/svg/director-class-fibre-channel-di.svg'), (5, 'static/management/svg/firewall-service-module-fwsm.svg'), (6, 'static/management/svg/firewall.svg'), (7, 'static/management/svg/generic-gateway.svg'), (8, 'static/management/svg/ios-firewall.svg'), (9, 'static/management/svg/layer-3-switch.svg'), (10, 'static/management/svg/nexus-2000-fabric-extender.svg'), (11, 'static/management/svg/nexus-5000.svg'), (12, 'static/management/svg/nexus-7000.svg'), (13, 'static/management/svg/route-switch-processor.svg'), (14, 'static/management/svg/router-firewall.svg'), (15, 'static/management/svg/accesspoint.svg'), (16, 'static/management/svg/wireless-router.svg'), (17, 'static/management/svg/workgroup-switch.svg'), (18, 'static/management/svg/cloud.svg'), (19, 'static/management/svg/fibre-channel-fabric-switch.svg'), (20, 'static/management/svg/ground-terminal.svg'), (21, 'static/management/svg/mesh-ap.svg'), (22, 'static/management/svg/modem.svg'), (23, 'static/management/svg/netflow-router.svg'), (24, 'static/management/svg/telecommuter-house.svg'), (25, 'static/management/svg/vpn-gateway.svg'), (26, 'static/management/svg/wavelength-router.svg')], default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.IntegerField(choices=[(0, 'Nonactive'), (1, 'Active'), (2, 'ToBin')], default=1),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
