# Generated by Django 3.2.7 on 2021-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20211028_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='secret',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
