# Generated by Django 3.2.7 on 2021-10-07 20:45

from django.db import migrations, models
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20211007_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(error_messages={'blank': 'This field is mandatory.', 'null': 'This field is mandatory.'}, help_text='Hexadecimal representation of colour, for example #73a6ff.', max_length=64, validators=[management.validators.ColorValidator]),
        ),
    ]
