# Generated by Django 3.2.7 on 2021-10-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_devicedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='domain_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='spanning_tree_mode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
