# Generated by Django 3.2.7 on 2021-10-31 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20211030_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ping_status',
        ),
    ]
