# Generated by Django 3.2.7 on 2021-10-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_device_ping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
