# Generated by Django 3.2.7 on 2021-10-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(error_messages={'blank': 'This field is mandatory.', 'invalid': 'Enter an valid IP address or host name.', 'null': 'This field is mandatory.', 'unique': 'This field must be unique.'}, max_length=64, unique=True),
        ),
    ]
