# Generated by Django 3.2.7 on 2021-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_device_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.IntegerField(choices=[(0, 'autodetect'), (1, 'cisco_ios'), (2, 'cisco_xr'), (3, 'cisco_xe'), (4, 'cisco_nxos')], default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(error_messages={'blank': 'This field is mandatory.', 'null': 'This field is mandatory.', 'unique': 'This field must be unique.'}, help_text='Enter a valid IP address or hostname.', max_length=64, unique=True),
        ),
    ]
