# Generated by Django 3.2.7 on 2021-11-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20211101_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='memory_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
