# Generated by Django 3.2.7 on 2021-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20211010_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
