# Generated by Django 3.2.7 on 2021-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_devicedata_memory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='memory_available_percentage',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='memory_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='memory_total_mb',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='memory_used_percentage',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
