# Generated by Django 3.2.7 on 2021-10-10 20:38

from django.db import migrations, models
import django.utils.timezone
import management.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20211010_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagdevicerelation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, error_messages={'blank': 'This field is mandatory.', 'invalid': 'Enter the correct colour value. It must be a 3/6 character hexadecimal number with # on begining', 'null': 'This field is mandatory.'}, help_text='Hexadecimal representation of colour, for example #73a6ff.', max_length=64, null=True, validators=[management.validators.ColorValidator()]),
        ),
    ]
