# Generated by Django 3.2.7 on 2021-10-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20211010_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
