# Generated by Django 3.2.7 on 2021-11-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20211101_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicedata',
            name='cpu_totalavg',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='images_files_list',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='memory_available_percentage',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='memory_status',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='memory_total_mb',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='memory_used_percentage',
        ),
        migrations.RemoveField(
            model_name='devicedata',
            name='partitions_list',
        ),
    ]
