# Generated by Django 3.2.7 on 2021-11-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20211101_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='cpu_stats',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='memory_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
