# Generated by Django 3.2.7 on 2021-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='execute_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='execute_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='seconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='scheduler',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('execute_date__isnull', True), ('execute_time__isnull', False)), models.Q(('execute_date__isnull', False), ('execute_time__isnull', True)), _connector='OR'), name='automation_scheduler_value_matches_type'),
        ),
    ]
