# Generated by Django 3.2.7 on 2021-11-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20211106_1707'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduler',
            name='automation_scheduler_value_matches_type',
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='execute_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='execute_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='scheduler',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('execute_date__isnull', True), ('execute_time__isnull', False), ('seconds__isnull', False)), models.Q(('execute_date__isnull', False), ('execute_time__isnull', True), ('seconds__isnull', False)), models.Q(('execute_date__isnull', False), ('execute_time__isnull', False), ('seconds__isnull', True)), _connector='OR'), name='automation_scheduler_value_matches_type'),
        ),
    ]
