# Generated by Django 3.2.7 on 2021-11-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20211101_2135'),
        ('automation', '0002_auto_20211028_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceautomationpolicyrelation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.device'),
        ),
    ]
