# Generated by Django 3.2.7 on 2021-11-06 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20211106_1709'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduler',
            name='automation_scheduler_value_matches_type',
        ),
    ]
